<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Arganél Personalizado envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'bruno@desbravadornota10.com.br',
		'to' => 'bruno@desbravadornota10.com.br'
	),
	'fields' => array(
		'custom_U3011' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Email\" é obrigatório.',
				'format' => 'O campo \"Email\" possui um email inválido.'
			)
		),
		'custom_U3007' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Observação',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U4293' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Cor do Fundo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Cor do Fundo\" é obrigatório.'
			)
		),
		'custom_U4305' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Cor da Borda',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Cor da Borda\" é obrigatório.'
			)
		),
		'custom_U4317' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Cor do Logo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Cor do Logo\" é obrigatório.'
			)
		),
		'custom_U4329' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Cor da Espada',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Cor da Espada\" é obrigatório.'
			)
		),
		'custom_U4341' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Insira a Quantidade',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Insira a Quantidade\" é obrigatório.'
			)
		)
	)
);

process_form($form);
?>
